#!/bin/bash
clear

atualizar_os_links() {
    clear
    echo "atualizando os links..."
    php cron.php
}

criar_super_usuario() {
    clear
    migrar_tabelas
    echo "criando usuário..."
    php bin/superUser.php
}

deploy() {
    clear
    echo "atualizando o repositório..."
    git pull origin master
    echo "git pull ok"
    migrar_tabelas
}

migrar_tabelas(){
    echo "migrando as tabelas..."
    php migrate.php
}

if [ -z "$1" ]
	then
        echo "Digite a opção:"
        echo "0) migrar tabelas"
        echo "1) deploy"
        echo "2) atualizar os links"
        echo "3) criar super usuário"
        printf "Opção número "
		read opt
	else
		opt=$1
fi

case $opt
in
    0) clear && migrar_tabelas ;;
    1) deploy ;;
    2) atualizar_os_links ;;
    3) criar_super_usuario ;;
    *) echo "opção inválida" ;;
esac
