<?php
helper("signin");
if(getMethod()=='POST'){
    $user=signin();
    if(isset($user['error'])){
        $data['error']=$user['error'];
        view('signin',$data);
    }else{
        redirect('/dashboard');
    }
}else{
    view('signin');
}
?>
