<?php
helper("auth");
if(getMethod()=='POST'){
    $user=signin();
    if(isset($user['error'])){
        $data['error']=$user['error'];
        view('signin',$data);
    }else{
        redirect('/dashboard');
    }
}elseif(isAuth()){
    redirect('/dashboard');
}else{
    view('signin');
}
?>
